### ISSUE TITLE
Required html input field shows `required=""` in `InlineSnapshot`

### ISSUE THREAD

**Issue by mithi** [testing-library/react-testing-library#1013]
- `@testing-library/react` version: `11.2.5`
- Testing Framework and version: JEST: `27.0.3`
- DOM Environment: 
- "@testing-library/jest-dom": `^5.16.1`,
  
### Relevant code or config:

```js
describe('html input field', () => {
  it('should be required', () => {
    const { baseElement } = render(<input name="my-input" required />);
    expect(baseElement).toMatchInlineSnapshot(`
<body>
  <div>
    <input
      name="my-input"
      required=""
    />
  </div>
</body>
`);
  });
});
```

### Problem description:

The inline snapshot of an html input with a required attribute is not what is expected. 

Just wanted to put this out there incase this isn't a known issue. Could be related to: 

- https://github.com/jsdom/jsdom/issues/2898
- https://github.com/testing-library/react-testing-library/issues/607
- https://github.com/testing-library/react-testing-library/issues/729

Feel free to close if there's a good reason to do so. Thank you!

**Comment by eps1lon** [comment]
Thanks for the detailed report.

This is intended behavior since React will actually add the `required` **attribute** when setting the `required` **prop**.

You can verify this with `ReactDOM.renderToString(<input required />); // <input required="" />`: https://codesandbox.io/s/required-prop-adds-required-attribute-ilinr?file=/src/index.js
