### ISSUE TITLE
Warning: The current testing environment is not configured to support act(...) when running with React 18

### ISSUE THREAD

**Issue by m4theushw** [testing-library/react-testing-library#1025]
- `@testing-library/react` version: 13.0.0-alpha.6
- Testing Framework and version: mocha 9.2.1
- DOM Environment: jsdom 19.0.0

### What you did:

I'm migrating https://github.com/mui-org/material-ui-x to React 18.

### What happened:

When I run the unit tests I get the following warning immediately after `render(<Component />)`:

```
console.error
    Warning: The current testing environment is not configured to support act(...)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at isConcurrentActEnvironment (node_modules/react-dom/cjs/react-dom.development.js:25064:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27365:12)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25299:5)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:28651:14)
      at ReactDOMRoot.Object.<anonymous>.ReactDOMHydrationRoot.render.ReactDOMRoot.render [as render] (node_modules/react-dom/cjs/react-dom.development.js:29063:3)

  console.error
    Warning: The current testing environment is not configured to support act(...)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at isConcurrentActEnvironment (node_modules/react-dom/cjs/react-dom.development.js:25064:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27365:12)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25299:5)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:28651:14)
      at node_modules/react-dom/cjs/react-dom.development.js:29086:7
```

Since our testing environment is configured to fail whenever `console.warn` is called I can't proceed.

### Reproduction:

https://github.com/m4theushw/dom-testing-library-template

We use mocha but this is irrelevant here. I changed a bit the example to run the tests with `jest` instead of `react-scripts test`. With `react-scripts test` I don't get the warning. I also added a custom babel configuration.

### Suggested solution:

Debugging the code I found that below `getGlobalThis()` returns `self` so `self.IS_REACT_ACT_ENVIRONMENT=true`.

https://github.com/testing-library/react-testing-library/blob/ba24a4be96469a5c3e004c186e19c1a57b2fd999/src/act-compat.js#L22-L23

But when React [checks](https://github.com/facebook/react/blob/72a933d2892dac9e5327678b6bd37af8d589bb22/packages/react-reconciler/src/ReactFiberAct.new.js#L44) if the update was wrapped in `act`, the `IS_REACT_ACT_ENVIRONMENT` is `undefined` causing the warning to be emitted.

I suppose that because of the babel config, the properties set on `self` are not available to React. If I change to `global.IS_REACT_ACT_ENVIRONMENT=true` then React sees the flag defined and I don't get the warning.

**Comment by eps1lon** [comment]
Do you have a specific branch+command I can check out? Or a cloneable repro? 

We had no issues with this approach in the MUI core repo

**Comment by eps1lon** [comment]
Whoops I just scanned and didn't see the repro link. In the future, please include a lockfile in the repro. Versions like `^18.0.0-rc.2`  are pretty dangerous since any version change may be considered breaking. Especially since `^18.0.0-rc.2` works a bit odd for React considering it matches e.g. `18.0.0-rc.0-next-fe905f152-20220107`.

I'll take a look what's wrong with our current approach. Probably need to copy what React considers "global" (i.e. `globalThis`).

**Comment by eps1lon** [comment]
As far as I can tell this is a bug with `jsdom-global`. global `self` i.e. [`window.self` refers to the window itself](https://developer.mozilla.org/en-US/docs/Web/API/Window/self).

Browser behavior:
![screenshot of browser devtools console with the input from below](https://user-images.githubusercontent.com/12292047/157603156-e29b589c-833b-4e99-ac2c-bc2290a509be.png)

```bash
> self.IS_REACT_ACT_ENVIRONMENT = true
<- true
> IS_REACT_ACT_ENVIRONMENT
<- true
```

Note that mixing environments (like `jsdom-global` does) is always a bit dangerous since these aren't real environments. So extra care needs to be taken that everything works as expected in each environment.

Will think about how to best address this.

**Comment by m4theushw** [comment]
JSDOM indeed overrides `self` with a different object than the used by React: https://github.com/jsdom/jsdom/blob/a604d67995fe5b2b1ce73090d347c23eeed011eb/lib/jsdom/browser/Window.js#L357

For now I'm setting `global.IS_REACT_ACT_ENVIRONMENT=true` before the tests to snooze the warning.

**Comment by eps1lon** [comment]
> JSDOM indeed overrides `self` with a different object than the one seen by React: [jsdom/jsdom@`a604d67`/lib/jsdom/browser/Window.js#L357](https://github.com/jsdom/jsdom/blob/a604d67995fe5b2b1ce73090d347c23eeed011eb/lib/jsdom/browser/Window.js#L357)

But this doesn't seem to be the same `self` that exists globally when using `jsdom-global`. If you write to `window.self.IS_REACT_ACT_ENVIRONMENT` then `IS_REACT_ACT_ENVIRONMENT` is defined. But if you write it `self.IS_REACT_ACT_ENVIRONMENT` in your repro, then `IS_REACT_ACT_ENVIRONMENT` isn't defined. This is a bug in how `self` is defined in your environment. Not with `jsdom`: https://runkit.com/eps1lon/622ba408f30d390009e293bd

I checked the `globalThis` shim and the recommendation of MDN and both check `self` first:
- [`globalThis` shim](https://github.com/es-shims/globalThis/blob/65891e4d285ae04e216ff01160cff861e0e41a4f/implementation.browser.js#L5)
- [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#examples)

So I'd rather not change the code for a library that's 5 years old. Especially since Jest seems to have figured this out properly.

> For now I'm setting global.IS_REACT_ACT_ENVIRONMENT=true before the tests to snooze the warning.

This is what we recommend anyway for these type of tests.
