### ISSUE TITLE
Focussing an element doesn't trigger the CSS update based on the :focus pseudo class

### ISSUE THREAD

**Issue by tbelch-at-eHealth-Tec** [testing-library/react-testing-library#1053]
- `@testing-library/react` version: 12.1.4
- Testing Framework and version: jest 27.5.1
- DOM Environment: jsdom 16.7.0

### Relevant code or config:

```js
// App.js
<input
  id="focus_input"
  data-testid="focus_input"
  type="text"
  defaultValue="Focus me"
/>{" "}
<label id="focus_label" data-testid="focus_label">
  Focus input to hide
</label>

//styles.css
#focus_input:focus + #focus_label {
  display: none;
}

//App.test.js
test("Hide on focus", () => {
  renderWithStyle("#focus_input:focus + #focus_label { display: none; }");

  expect(screen.getByTestId("focus_label")).toBeVisible();

  act(() => {
    screen.getByTestId("focus_input").focus();
  });
  expect(screen.getByTestId("focus_input")).toHaveFocus();

  expect(screen.getByTestId("focus_label")).toHaveStyle({ display: "none" });
  expect(screen.getByTestId("focus_label")).not.toBeVisible();
});
```

### What you did:

Using the CSS pseudo class `:focus` to determine whether an element has the style `display: block` or `none`.

### What happened:

I'm running a Test with `@testing-library/react` to check whether or not the element is visible, based on the focused element. I can focus the element, but the other ones styling still hasn't changed.

I created the same example using the `:checked` pseudo class. This is working!

### Reproduction:

You can use the following https://codesandbox.io/s/trusting-leavitt-odukyk to check it out. Both examples (`:focus` and `:checked`) are present. Both work fine in the browser. But only the `:checked` test case is successful. (The css is manually added to the tests, because CSS that is imported in React components, isn't automatically added to jsdom.)

### Problem description:

I expect the styling of the sibling component to change, when the controlling component is focused. The same way it happens in the browser.

### Suggested solution:

Sorry, I can't provide one.

**Comment by MatanBobi** [comment]
Hi @tbelch-at-eHealth-Tec, thanks for the detailed reproduction :)
We're actually not the ones calculating the styles, that's JSDOM, we only assert on them in jest-dom.
Given your example, I built this one which relies only on JSDOM, please let me know if you think it's the same and if it does, we should open a ticket in JSDOM because I wasn't able to find one:
https://codesandbox.io/s/jsdom-focus-sibling-combinator-ph3tql?file=/src/index.js

**Comment by tbelch-at-eHealth-Tec** [comment]
Hi @MatanBobi, thank you for your quick response.

To be honest, I already had my suspicions and thought that I should direct my questions to the jsdom team. Anyhow, I thought it would be fair to start at the beginning. ;)

I'll move to jsdom with this. Thank you!

**Comment by NickGard** [comment]
There's a [comment on the JSDOM bug](https://github.com/jsdom/jsdom/issues/3359#issuecomment-1409853971) linked that claims the bug is fixed. I've tried to update to the latest package locally, but it looks like `jsdom` is a transitive dependency for many direct dependencies (all under the `@testing-library` npm namespace). Are there any plans to update the libraries to use the latest `jsdom`?
