### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80 if an axios fetch gets initialized outside of a react component react-testing-library/msw

### ISSUE THREAD

**Issue by chloe-samdesk** [testing-library/react-testing-library#1054]
I'm getting the ECONNREFUSED error and it looks like my msw server isn't catching my get request when I start a get outside of a React component (which shaves some time off of the response).

When axios.get is uses inside of the useEffect everything works as normal and the msw picks up the request with no errors. Is there a special way to setup react-testing-library with msw so that I can initialize an axios.get() outside of react components and then have the component pick up the promise once it's loaded.

Thanks, get tool, but I just couldn't find how to get this working.

```
const signinPromise = axios.get(`signin?ajax=true`);

const Index = () => {
    useEffect(() => {
        (async () => {
            try {
                const response = await signinPromise;
                // ... do something with data etc
            } catch (err) {
            } finally {
            }
        })();
    }, []);

    return <>{/* content here */}</>;
};


```

I also asked on SO. https://stackoverflow.com/questions/71961138/error-connect-econnrefused-127-0-0-180-if-an-axios-fetch-gets-initialized-outs

**Comment by MatanBobi** [comment]
Hi @chloe-samdesk, this isn't really related to testing-library and the best place for these kind of questions is definitely stackoverflow.
My guess is that since you trigger the `get` request when you import the component (since that's the first time this file is being ran), it's triggering the get request before msw starts listening. You can try using dynamic import or `require` to import the component file within the test and that might fix it.
Anyways, I'm closing this one as this is not in our scope as part of this package :)
