### ISSUE TITLE
Cleanup before microtasks run

### ISSUE THREAD

**Issue by atomiks** [testing-library/react-testing-library#1073]
- `@testing-library/react` version: latest

Right now cleanups occur in a microtask but this causes issues with libraries that perform state updates in microtasks. Even when guarding with `isMounted`, an `act` warning gets printed.

```js
function App() {
  const [x, setX] = useState(null);
  const mountedRef = useMounted();
 
  const measure = useCallback(node => {
    Promise.resolve().then(() => {
      // `cleanup()` hasn't been invoked yet
      // so this guard does not help!
      if (mountedRef.current) setX(10);
    });
  }, []);

  return <div ref={measure} style{{left: x ?? ''}} />
}

test('test', () => {
  render(<App />);
  // `measure` microtask starts
});

// Test finishes, `cleanup()` gets put in the microtask queue, AFTER the component's one.
// So the microtask is still active and prints an `act` warning as the state update occurs
// after the test is done.
```

Is it possible to either:

- Cleanup before microtasks can run, or
- Wait for the microtask queue to finish?

I think this may be an issue of when Jest calls `afterEach()` and may not be solvable in Testing Library itself. This has been an annoying problem for users testing Popper/Floating UI and requires users to flush the queue manually or explicitly call `cleanup()` at the end of their test to avoid the act warning.

**Comment by eps1lon** [comment]
I encountered similar issues with Popper. I think I fixed most issues with a dangling `await act(() => Promise.resolve())`.

But we can't really fix this in our side since we would break existing code that relies on the timing of automatic cleanup.

However, you can always disable automatic cleanup by importing from `@testing-library/pure` and ensure on your own that cleanup happens at the proper timing.
