### ISSUE TITLE
Cannot find module 'react-dom/test-utils' from 'node_modules/@testing-library/react/dist/act-compat.js'

### ISSUE THREAD

**Issue by gpspake** [testing-library/react-testing-library#1078]
- `@testing-library/react` version: 13.2.0
- Testing Framework and version: jest"@28.1.0
- DOM Environment: jest-environment-jsdom@28.1.0

### Relevant code or config:
link to tagged codebase with issue https://github.com/gpspake/ui-next/tree/v1.0.4

### What you did:

I'm trying to run tests using the latest versions of Jest and react testing library in a TS/React component library project using a pretty minimal configuration. For reference, the project is based on [this guide](https://dev.to/alexeagleson/how-to-create-and-publish-a-react-component-library-2oe)

### What happened:

Here's the error I'm getting when I attempt to run tests
```js
● Test suite failed to run

Cannot find module 'react-dom/test-utils' from 'node_modules/@testing-library/react/dist/act-compat.js'

Require stack:
  node_modules/@testing-library/react/dist/act-compat.js
  node_modules/@testing-library/react/dist/index.js
  src/components/Icon/Icon.test.tsx

  at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
  at Object.<anonymous> (node_modules/@testing-library/react/dist/act-compat.js:10:41)
```

### Reproduction:

```
git clone -b v1.0.4 git@github.com:gpspake/ui-next.git
cd ui-next
yarn
yarn test
```

### Problem description:

This problem was previously discussed in #315 but it's been a while and the context seems different in that I'm just trying to render a component in my test.

### Suggested solution:

I'm not sure 😅

**Comment by MatanBobi** [comment]
Hi @gpspake!
As you can see in the [package.json](https://github.com/testing-library/react-testing-library/blob/main/package.json#L64) file, `react-dom` is a peerDependency for `@testing-library/react` so we just can't operate without it.
I'm not sure who wrote the guide, but there's no way to use our library without having `react-dom` installed, sorry.
The reason is, we're using `act` from `react-dom/test-utils` which is a react-dom wrapper to make it run as close as it can to the way react-dom behaves in the browser (when it comes to flushing events etc.).

I'm closing this one :) Feel free to comment with further questions, me and all the other maintainers are here.

**Comment by gpspake** [comment]
Oh... duh 🤦 😂 It's right there in the error. I guess I assumed I already had it installed. 
Installing react-dom fixed the issue. Thanks @MatanBobi!

**Comment by verifiedanswer** [comment]
[[Solved] Cannot find module ‘react-dom/client’ from ‘node_modules/@testing-library/react/dist/pure.js’](https://verifiedanswer.com/cannot-find-module-react-dom-client-from-node-modules-testing-library-react-dist-pure-js/)

**Comment by emmacv** [comment]
Life savior for react native devs
