### ISSUE TITLE
Examples in Codesandbox cannot be run

### ISSUE THREAD

**Issue by magnattic** [testing-library/react-testing-library#1109]
### What you did:

Tried to run the [examples](https://testing-library.com/docs/example-codesandbox/) online in the [codesandbox](https://codesandbox.io/s/github/kentcdodds/react-testing-library-examples/tree/main/).

### What happened:

I couldn't figure out how. Is it even possible?
The documentation states:

>The idea is that most of the tests should be runnable in codesandbox to make it easy to try things out, fork, contribute, etc. Either clone the repo locally or run the tests in a terminal in codesandbox (run "npm test") and it should watch your changes in the codesandbox and re-run the tests as you make changes.

Where do you enter `npm test`?

All I can find is this: 
![image](https://user-images.githubusercontent.com/7560166/183903175-cf9842d1-df1c-4e33-b395-45a04c710eef.png)

### Reproduction:

- Go to https://codesandbox.io/s/github/kentcdodds/react-testing-library-examples/tree/main/
- Read the text documentation there
- Be confused on what to do next

### Suggested solution:

Fix the codesandbox or make it clearer in the documentation how to run it.

**Comment by MatanBobi** [comment]
Hi @magnattic, thanks for taking the time to open this one.
You can definitely take every example there and try to run it locally. Running tests in codesandbox isn't the best idea because it might have some issues.
If you still want to run those in codesandbox, I suggest opening an issue at https://github.com/kentcdodds/react-testing-library-examples because these examples aren't hosted under the testing-library organization.

Can you please reference me to the place where this quote sits? I'm not sure we'd want to tell people to run the tests in codesandbox as an approach.

**Comment by magnattic** [comment]
It's right there in the index.js of the codesandbox: 
![image](https://user-images.githubusercontent.com/7560166/185103555-fe8beffc-145d-494f-a50b-463494e6368d.png)

**Comment by MatanBobi** [comment]
If that's the case, I'm closing this one and I highly recommend opening an issue in that [repo](https://github.com/kentcdodds/react-testing-library-examples) as it's not in our control..
Thanks for reporting this one :)
