### ISSUE TITLE
Using your libraries in my custom made code editor gives me following error in preview window: Error: act(...) is not supported in production builds of React

### ISSUE THREAD

**Issue by ldco2016** [testing-library/react-testing-library#1232]
- `@testing-library/react` version: assuming latest version
- Testing Framework and version: assuming latest version
  
- DOM Environment: Chrome browser v115
  

### Relevant code or config:

```js
import produce from "immer";
import { ActionType } from "../action-types";
import { Action } from "../actions";
import { Cell } from "../cell";

interface CellsState {
  loading: boolean;
  error: string | null;
  order: string[];
  data: {
    [key: string]: Cell;
  };
}

const initialState: CellsState = {
  loading: false,
  error: null,
  order: [],
  data: {},
};

const initialCodeSnippets = [
  `import React, { useState } from 'react';
  import { render, screen } from '@testing-library/react';
  import user from '@testing-library/user-event';
  
  const Counter = () => {
    const [count, setCount] = useState(0);
    return <button onClick={() => setCount((c) => c + 1)}>Count: {count}</button>
  };
  render(<Counter />);`,
  `test('it shows a button', () => {
    render(<Counter />);

    const button = screen.getByRole('button');
    
    expect(button).toBeInTheDocument();
  });`,
  `test('it doesnt show an input', () => {
    render(<Counter />);

    const input = screen.queryByRole('textbox');

    expect(input).not.toBeInTheDocument();
  });`
  // Add more initial snippets as needed
];

const reducer = produce((state: CellsState = initialState, action: Action) => {
  switch (action.type) {
    case ActionType.UPDATE_CELL:
      const { id, content } = action.payload;

      state.data[id].content = content;
      return state;
    case ActionType.DELETE_CELL:
      delete state.data[action.payload];
      state.order = state.order.filter((id) => id !== action.payload);

      return state;
    case ActionType.MOVE_CELL:
      const { direction } = action.payload;
      const index = state.order.findIndex((id) => id === action.payload.id);
      const targetIndex = direction === "up" ? index - 1 : index + 1;

      if (targetIndex < 0 || targetIndex > state.order.length - 1) {
        return state;
      }

      state.order[index] = state.order[targetIndex];
      state.order[targetIndex] = action.payload.id;

      return state;
    case ActionType.INSERT_CELL_AFTER:
      const cell: Cell = {
        content: initialCodeSnippets[action.payload.orderIndex],
        type: action.payload.type,
        id: randomId(),
        orderIndex: action.payload.orderIndex,
      };

      state.data[cell.id] = cell;

      const foundIndex = state.order.findIndex(
        (id) => id === action.payload.id
      );

      if (foundIndex < 0) {
        state.order.unshift(cell.id);
      } else {
        state.order.splice(foundIndex + 1, 0, cell.id);
      }

      return state;
    default:
      return state;
  }
}, initialState);

const randomId = () => {
  return Math.random().toString(36).substring(2, 5);
};

export default reducer;

```

### What happened:

I added the import statements for this library inside of backticks to display as initial value in my custom code editor and in the preview wwindow where the code is supposed to appear I instead get a message saying:

Error: act(...) is not supported in production builds of React.

### Reproduction:

You can git clone it and reproduce it from here:

https://github.com/ldco2016/rtl-sheets/tree/experimenting

Someone suggested that I install the react-testing-library into the application itself but that did not resolve the issue.

**Comment by MatanBobi** [comment]
Hi @ldco2016, thanks for opening this.
Under the hood, when you're calling `render`, we're wrapping that function in `act` to make the test run as similar to how it runs in the browser as it can. That's why you're getting this error. Since you're not running that code inside a test environment, `act` is not supported. That's a React thing, not a testing-library thing. There are some workarounds for this, but I don't think they are good. The main problem is that you're using the production build of React to run tests.
I'm closing this as this isn't something related to testing-library, thank you :)

**Comment by MatanBobi** [comment]
This patching isn't really doing what our `render` function is doing. If you're planning on running tests, using `act` is mandatory from React's perspective in order to run assertions on elements after all effects were flushed.
Besides `render`, the `unmount` function is also wrapped in `act` and so are `waitFor`, `findBy` and some more I might be missing. I highly recommend not to go with the approach you're taking.
