### ISSUE TITLE
Test layout.tsx file without having validateDOMNesting warning

### ISSUE THREAD

**Issue by mezzouhri** [testing-library/react-testing-library#1250]
### Describe the feature you'd like:

As a user of react 18 with NextJS (with app directory), I would like to test routLayout.tsx file without having this warning : `Warning: validateDOMNesting(...): <html> cannot appear as a child of <div>.
        at html
        at children`
     
```
//routLayout.tsx:

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" data-testid="rout-layout">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
```

### Suggested implementation:

Maybe by modifying the [container](https://testing-library.com/docs/react-testing-library/api#container) options 

Thank you so much for your help

**Comment by eps1lon** [comment]
This is a React 19 feature. In React 18 you can't render into `document`, only hydrate.

In React 19, you'd just do `render(<App />, { container: document })`. In React 18, you'd have to prepare hydrateable HTML first and then do `render(<App />, { container: document, hydrate: true })`.

All we have to do on the RTL side is ensure we properly type `container` based on `hydrate`.

> If you don't mind the TS error, you can workaround this by doing something like this:
[stackblitz.com/edit/rtl-template-68mwxh?file=src%2FApp.test.tsx](https://stackblitz.com/edit/rtl-template-68mwxh?file=src%2FApp.test.tsx)

You shouldn't do this in React 18 since that's not supported.

**Comment by MatanBobi** [comment]
> You shouldn't do this in React 18 since that's not supported.

That's why I was using the canary release in my stackblitz, the typing for the canary release support this, isn't that enough?

**Comment by eps1lon** [comment]
Yeah Canary should be fine. Then all we need is https://github.com/testing-library/react-testing-library/pull/1304
