### ISSUE TITLE
Add option to enable strict mode render

### ISSUE THREAD

**Issue by alexkrolick** [testing-library/react-testing-library#338]
Why: to test that components work in concurrent React

**Comment by kentcdodds** [comment]
I understand the motivation, but couldn't this be accomplished using the wrapper option?

**Comment by alexkrolick** [comment]
Hmm, yes. I thought you have to change the `ReactDOM.render()` call

**Comment by kentcdodds** [comment]
We would if we wanted to run concurrent mode. Maybe we will when that's stable, but I kinda don't think we will want/need to. We'll see.

**Comment by penx** [comment]
> We would if we wanted to run concurrent mode. Maybe we will when that's stable, but I kinda don't think we will want/need to. We'll see.

@kentcdodds sooo.... how about now? 😀

Coming to this issue as I have a hook that is behaving incorrectly in strict mode during development and I'd like to write a failing test before writing the fix.

I'll look in to the wrapper option.

**Comment by penx** [comment]
I see I can add `wrapper: React.StrictMode` to options:

```tsx
    renderHook(() => useMyHook(), {
      wrapper: React.StrictMode,
    });
```

Unfortunately I'm pretty sure this is running React in production mode so isn't double calling `useMemo` as per https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

I don't see a way to make Jest/react-testing-library run React in development mode, perhaps there is one and I've missed it.

Obviously I want my hook to work in development mode (and I'm pretty sure there's an underlying issue here I'd need to solve anyway) and I'd really like to write a test to show this first.

Any thoughts?

**Comment by penx** [comment]
>  it isn't double-invoking `useMemo` as per https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects
I think this assumption was due to React 17 silencing the console during double invoking.

Jest runs React with NODE_ENV by default, so
- upgrading to React 18 
- using the new renderHook from react-testing-library (rather than react-hooks-testing-library) 
- using wrapper: React.StrictMode

Seems to be all I need to do to test my hook works when double invoking  😓

**Comment by smmoosavi** [comment]
> I understand the motivation, but couldn't this be accomplished using the wrapper option?

Yes, The wrapper option can, but sometimes we need it for other components (e.g. `DataProvider`); strict options make it easier. 

also, I think it could be good that we have a strict option enabled by default

**Comment by nickmccurdy** [comment]
Is there a reason not to enable this by default? Considering Create React App and Vite already default to enabling it.

**Comment by eps1lon** [comment]
Not a fan of altering the test input. Especially since StrictMode will break perfectly fine test (e.g. asserting the number of console calls). 

The general advise has always been to use an internal wrapper instead. That is a good place to add StrictMode (we did that in MUI).

**Comment by eps1lon** [comment]
`initialProps` is for the hook not the wrapper component.

**Comment by paul-sachs** [comment]
@eps1lon I thought that as well, but the types complained when i tried it. Perhaps that's just a problem with the types:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/11449728/228637940-264a26f5-6886-4de6-bfa4-47e534da3a52.png">

**Comment by paul-sachs** [comment]
Ah yeah, this library is using `@testing-library/react-hooks`, so you're right, that's a different repo. Sorry, clearly I got turned around.

**Comment by eps1lon** [comment]
Yeah let's do this. I think it's currently a bit too verbose if you want StrictMode and a custom `wrapper`. Especially if we want to encourage testing in StrictMode to flush out issues when concurrently rendering early. 

Not sure if we want to go with `strict` though in case we want to use that for something testing-library related. `strictMode` has a more obvious connection with `React.StrictMode`. Does anybody have a preference here?

**Comment by nickmccurdy** [comment]
We could borrow Next's `reactStrictMode` boolean option.

**Comment by eps1lon** [comment]
The react prefix feels redundant here but using something familiar is a good enough argument to lean towards `reactStrictMode`. 

And this option could also take its default from the configuration. That way verbosity isn't too much of an issue since you can likely opt-into StrictMode and then slowly fix the `reactStrictMode: false` instances.

**Comment by nickmccurdy** [comment]
> The react prefix feels redundant here but using something familiar is a good enough argument for me to lean towards `reactStrictMode`.

My primary concern with `strictMode` is that it could be mistaken for JavaScript's strict mode, which affects CJS modules (like React) in Node (but not ESM, which is always strict). Additionally I'm considering bundling APIs for [RSC](https://github.com/testing-library/react-testing-library/issues/1209) or [SSR](https://github.com/testing-library/react-testing-library/issues/1120) support, in which case  toggling JS features like strict mode would be in the domain of RTL (or a supplemental package, I'll propose a specific architecture when I'm ready).

> And this option could also take its default from the configuration. That way verbosity isn't too much of an issue since you can likely opt-into StrictMode and then slowly fix the `reactStrictMode: false` instances.

Are you referring to some existing config like `next.config.js`?

**Comment by eps1lon** [comment]
> Are you referring to some existing config like next.config.js?

The one we have in `@testing-library/react` under `configure()`.  For now we would default to `reactStrictMode: false` though and then discuss later if we want to flip it in a new major release.

**Comment by yinm** [comment]
Can I try this issue?

**Comment by eps1lon** [comment]
Fixed in https://github.com/testing-library/react-testing-library/pull/1241
