### ISSUE TITLE
Ability to interact with <select multiple> tags

### ISSUE THREAD

**Issue by michaellasky** [testing-library/react-testing-library#375]
### Describe the feature you'd like:

Currently there doesn't seem to be any programmatic way of interacting with &lt;select multiple &gt; tags through fireEvent.  With a normal &lt;select&gt; tag you can at least call fireEvent.change(select, { target: { value: 'Selected Value' } }), but select multiple tags use a separate HTMLOptionsCollection object attached to the event object to signify selected options.  HTMLOptionsCollection can't be constructed, and passing any other mock object results in a cryptic TypeError.  

     const options = { ...obj structure mirroring HTMLOptionsCollection... };
     fireEvent.change(selectMultiple, { target: { options } });

results in:
   
     "TypeError: 'set' on proxy: trap returned falsish for property 'options'"

### Suggested implementation:

Something like fireEvent.chooseOptions(selectMultiple, [opt1, opt2]);  

chooseOptions is a bad name, but select() is already taken.  

### Describe alternatives you've considered:

Currently this can be worked around (thanks GreenJello in #reactjs) with something like the following:
 
           Array.from(selectMultiple.children, (option, i) => {
                  if (i === 0 || i === 1) { option.selected = true; }
            });

             fireEvent.change(selectMultiple);

which will programmatically select options 0 and 1 in test.  I can then programmatically submit the form (fireEvent.submit(submitButton)) and those options are submitted. 

### Teachability, Documentation, Adoption, Migration Strategy:

TBD

**Comment by kentcdodds** [comment]
Hmmm... Interesting. Do you have any idea how this might be implemented?

**Comment by NuclearHorseStudios** [comment]
I'm not sure off hand because I haven't yet dug into the react-testing-library source to see what might make sense, but I'd imagine it could be something like the workaround above.  Some function that takes a DOM element (the select), and maybe a function that the options get mapped over and returns true if the option should be selected?

In the example above, if I wanted to select the 1st and 2nd option, it'd look like:

      fireEvent.chooseOptions(selectMultiple, (option, idx) => idx === 0 || idx === 1); 

or select based on the option itself

      fireEvent.chooseOptions(selectMultiple, (option, idx) => option.value === 'Some expected value'); 

Just spitballing.  If i have time later this week I'll look into it more and see if I can get a working implementation or if any of that even makes sense in that context.

**Comment by kentcdodds** [comment]
Hmm... I'd rather that this go in https://github.com/testing-library/user-event

Seems like it'd make more sense there. `fireEvent` should only be for actually browser events.

Please file an issue there. Thanks!
