### ISSUE TITLE
fireEvent.keyPress does not trigger a focused button

### ISSUE THREAD

**Issue by andraz** [testing-library/react-testing-library#376]
- `react-testing-library` version: 7.0.1
- `react` version: 16.8.6

### Relevant code or config:

```js
    fireEvent.keyPress(button, { key: 'Enter', code: 13, charCode: 13 })
```

### What you did:

Used info from #269 how to trigger keyPress in test.

### What happened:

Did not trigger keyPress in test.

### Reproduction:

https://codesandbox.io/s/reacttestinglibrary-testing-button-8bfqb

### Problem description:

Button works as expected when you manually press the enter key on it.

Test does not simulate button press when fireEvent.keyPress triggers.

**Comment by rambabusaravanan** [comment]
Wherever I go, I see your face. I mean only `fireEvent.change` and `fireEvent.click`. I couldn't find any examples for `fireEvent.focus` or `fireEvent.keyPress`.

I want to test the keyboard accessibility (like tab, arrow keys, space to check/uncheck) for my checkbox
```tsx
it("focuses 'in' on tab", async () => {
  let cb = { onBlur: jest.fn(), onFocus: jest.fn(), onChange: jest.fn() };
  let values = ["sms", "call"];

  let { container } = render(
    <>
      <input name="before" className="before" />
      <CheckboxGroup name="channel" options={options} value={values} {...cb} />
      <input name="after" className="after" />
    </>
  );

  // 1.focus on prev
  let elemIp1 = container.getElementsByClassName("before")[0] as HTMLInputElement;
  act(() => elemIp1.focus()); // works👍found alternative for "fireEvent.focus(elemIp1)"
  // 1.verify focus in dummy textbox
  let activeEl = container.querySelector<HTMLInputElement>(":focus");
  expect(activeEl).toBe(elemIp1);
  if (!activeEl) return;

  // 2.press 'tab' and go to checkbox
  fireEvent.keyPress(activeEl, Keys.Tab);
  // 2.verify focus in checkbox
  let nextActiveEl = container.querySelector<HTMLInputElement>(":focus");
  expect(nextActiveEl).not.toBe(elemIp1); // fails here.
  /* ==>> nextActiveEl should now be checkbox and not prev textbox <<== */

  // 3.press 'space'
  if(!nextActiveEl) return
  act(() => nextActiveEl.dispatchEvent(new KeyboardEvent("keypress", Keys.Space)));
  // 3.verify values and callbacks
  expect(cb.onChange).toHaveBeenCalledWith(["sms"], "channel");
  // TODO: expect on focus to be called
});
```

I found a replacement for `fireEvent.focus(elemIp1)` as `act(() => elemIp1.focus())` and it works

I read somewhere, instead of `fireEvent.keyPress(activeEl, Keys.Tab)`, used like `activeEl.dispatchEvent(new KeyboardEvent("keypress", Keys.Tab))` but it is not working.

```
Keys.Tab = { key: "Tab", code: 9, charCode: 9 }
// also tried with
Keys.Tab = { which: 9, keyCode: 9, key: "Tab", code: "Tab", charCode: 0, shiftKey: false }
```

**In a nut shell, when my focus is in prev element, I need to trigger Tab, Arrows, Space and need to test checked/unchecked status of my component. How do I test keyboard navigations**

**Comment by kentcdodds** [comment]
I'm pretty sure the trouble you're having is because JSDOM doesn't support keyboard navigation semantics. You need to run your tests in a real browser for that. Unfortunately [not even Cypress supports the tab key currently](https://docs.cypress.io/api/commands/type.html#Tabbing) :-(

If you want to test this, then you should run your tests in a real browser like with Karma or puppeteer. react-testing-library works with Karma and for puppeteer you can use https://testing-library.com/docs/pptr-testing-library/intro

Good luck!

**Comment by DDDDDanica** [comment]
try `button.focus()`
