### ISSUE TITLE
Fireevent on type=reset button not triggering

### ISSUE THREAD

**Issue by hanikishorpinisetty** [testing-library/react-testing-library#393]
- `react-testing-library` version: 5.2.3
- `react` version: 16.8.6
- `node` version: 
- `npm` (or `yarn`) version:

### Relevant code or config:

```js
<button type='reset'>Reset</button>
fireEvent.click(getByText('Reset'));
```

### What you did:
I triggered fireEvent on type=reset button which is inside a form.

### What happened:
It's not triggering form onReset handler.

**Comment by kentcdodds** [comment]
I'm guessing this is a jsdom bug. Could you (or anyone else) do a little digging?

**Comment by viniciusavieira** [comment]
I'm looking into this.

**Comment by viniciusavieira** [comment]
I've been looking into this and I have some info.
If we look into this jsdom code 
https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/HTMLFormElement-impl.js#L87 

We can see it is supposed to handle the reset as expected, since the methods to reset are really implemented and passes on the lib tests(I've forked it and confirmed in local environment)

But if you really try to run the test as described by this issue, the tests does not pass, it does not call the reset as it should.
I've updated my local ```src/__tests__/form.js ``` like this:
```
import React from 'react'
import {render, fireEvent, cleanup} from '../'

afterEach(cleanup)

function Login({onSubmit, onReset}) {
  return (
    <div>
      <form
        onSubmit={e => {
          e.preventDefault()
          const {username, password} = e.target.elements
          onSubmit({
            username: username.value,
            password: password.value,
          })
        }}
        onReset={e => {
          e.preventDefault()
          onReset()
        }}
      >
        <label htmlFor="username-input">Username</label>
        <input id="username-input" placeholder="Username..." name="username" />
        <label id="password-label">Password</label>
        <input
          placeholder="Password..."
          type="password"
          name="password"
          aria-labelledby="password-label"
        />
        <button type="reset">Reset</button>
        <button type="submit">Submit</button>
      </form>
    </div>
  )
}

test('login form submits', () => {
  const fakeUser = {username: 'jackiechan', password: 'hiya! 🥋'}
  const handleSubmit = jest.fn()
  
  const {getByLabelText, getByText} = render(<Login onSubmit={handleSubmit}/>)

  const usernameNode = getByLabelText(/username/i)
  const passwordNode = getByLabelText(/password/i)
  const submitButtonNode = getByText(/submit/i)
  

  // Act
  usernameNode.value = fakeUser.username
  passwordNode.value = fakeUser.password
  fireEvent.click(submitButtonNode)

  // Assert
  expect(handleSubmit).toHaveBeenCalledTimes(1)
  expect(handleSubmit).toHaveBeenCalledWith(fakeUser)

})

test('login form resets', () => {
  const handleReset = jest.fn()

  const {getByText} = render(<Login onReset={handleReset}/>)

  const resetButtonNode = getByText(/reset/i)
  // Act
  fireEvent.click(resetButtonNode)

  // Assert
  expect(handleReset).toHaveBeenCalledTimes(1)
})

/* eslint jsx-a11y/label-has-for:0, jsx-a11y/aria-proptypes:0 */
```

And it does not pass:
![image](https://user-images.githubusercontent.com/2073019/60107539-7730d900-973d-11e9-9f9c-f21d07017a2e.png)

But if I change the behavior to button click and test it, it passes
```
<button type="reset" onClick={onReset}>Reset</button>
```
![image](https://user-images.githubusercontent.com/2073019/60107676-b101df80-973d-11e9-8f4a-ebc526e9543d.png)


I've forked jsdom and running the script tests for the api, all of them pass, so I'm not sure whats wrong, but I think this is a bug related to jsdom form reset itself.

**Comment by kentcdodds** [comment]
Thanks for this research!

Considering the fact that this is a bug in jsdom, an issue should be filed on jsdom (I recommend making a very simple reproduction following their guidelines rather than including react-testing-library into the mix).

There's nothing we can do within this project. jsdom will need to be fixed. In the mean time, if you want this test case covered, you'll have to run your tests in a real browser (I recommend testing this with Cypress along with your E2E tests, though you could also use Karma).

Good luck.
