### ISSUE TITLE
afterEach cleanup not clearing the DOM between async tests

### ISSUE THREAD

**Issue by CurtisHumphrey** [testing-library/react-testing-library#460]
- `@testing-library/react` version: 9.1.3
- `react` version: 16.9.0
- `node` version: 12.1.0
- `npm` (or `yarn`) version: 1.13.0

### Relevant code or config:

```js
it('test one', async () => {
  const { queryByText } = render(<Modal {...props} />);
  expect(queryByText('hi')).toBeInTheDocument();
  // test passes
})
it('test two', async () => {
  const { queryByText } = render(<Modal {...props} />);
  expect(queryByText('hi')).toBeInTheDocument();
  // test does not pass as there are two Modals in the dom so queryBy fails
})
```

### What you did:

Running two async tests in the same spec file

### What happened:

The first test has not cleaned up the dom before the second async test runs

**Comment by weyert** [comment]
Hmm, I am unable to reproduce this: 
https://nt06u.csb.app/

**Comment by kentcdodds** [comment]
Yes, you need to make sure that your Modal cleans up on unmount. For example: https://testing-library.com/docs/example-react-modal

**Comment by bigfoot31** [comment]
Facing the same issue with **asyc** tests. No modals, just simple dom tree. Tests have **api calls**.

I have two tests running in sequence as shown in the [top comment](https://github.com/testing-library/react-testing-library/issues/460#issue-483029623).

- The 2nd test fails due to extra elements in the dom-tree.
- If I only run the 2nd test then, 2nd test passes.
