### ISSUE TITLE
Context API - An update <NAME> inside a test was not wrapped in act(...)

### ISSUE THREAD

**Issue by JamesPortelli** [testing-library/react-testing-library#510]
- `react-testing-library` version: 9.3.0
- `react` version: 16.11.0
- `node` version: 11.13.0
- `npm` (or `yarn`) version: 6.7.0

### What you did:
When testing a component which is making use of the context api through a custom effect, an error is thrown in the console stating that an update wasnt wrapped within an act.

### What happened:
```
Warning: An update to PageLoaderProvider inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/ fire events that update state /
});
/ assert on the output /
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
in PageLoaderProvider (at App.js:8)
in div (at App.js:7)
in App (at tests/index.js:7)
```

### Reproduction:
CodeSandbox Project:
https://codesandbox.io/embed/react-testing-library-demo-u7ozk

**Comment by bcarroll22** [comment]
Hi James,

Not a bug with RTL, you just needed to declare the async function inside the effect. Since the effect is doing something async, React needs to know so it can handle the effect properly.

Also be sure to cleanup after any timeouts, intervals, etc. that you create during effects 👍 Good luck!

[Updated sandbox with no warning](https://codesandbox.io/s/react-testing-library-demo-3p54n)
