### ISSUE TITLE
SSR component testing

### ISSUE THREAD

**Issue by ruhaise** [testing-library/react-testing-library#561]
### Describe the feature you'd like:
Currently there is no documentation, recommendations or API's that I could find regarding testing components that are rendered in a server side context.

### Describe alternatives you've considered:
currently, I use the hack
```
/**
 * @jest-environment node
 */
import React from 'react'
import { renderToString } from 'react-dom/server'

const foo = () => <img src="bar.png"/>
describe('Server-side rendering', () => {
  it('renders on a server without crashing', () => {
    const foo = () => <img src="bar.png"/> 
    const renderOnServer = () =>
      renderToString(
        <main>
              <foo/>
        </main>,
      )
    expect(renderOnServer).not.toThrow()
  })

  it('renders with the src attribute', () => {
    const foo = () => <img src="bar.png"/>
    const ElementImageHtml = renderToString(<foo/>)
    expect(ElementImageHtml).toContain('src="bar.png"')
  })
})

```

**Comment by kettanaito** [comment]
I think what you may do is `console.log(typeof window)` in your test suite. If it's undefined the test is running in a NodeJS environment, which you can treat as server. If the window is defined, then it's up to the library to suggest a suitable solution, if any.

**Comment by ruhaise** [comment]
@kettanaito  in my case its NodeJS environment, I want to really know if there is a built-in API to test server-rendered components.

**Comment by kentcdodds** [comment]
Hi @ruhaise,

I'm not sure to be honest. What I normally recommend is what you have there, though I can see how it could be useful to be able to traverse the output like it is DOM. What if we did something like this:

```javascript
render(<ServerStuff />, {ssr: true})
```

I think what we'd do is basically:

```javascript
const string = renderToString(yourUI)
container.innerHTML = string
// etc...
```

So you'd be able to interact with it like it's DOM, but it won't run your effects/etc.

What do you (and other's who are reading this) think?

**Comment by kettanaito** [comment]
> So you'd be able to interact with it like it's DOM, but it won't run your effects/etc.

When would you want to interact with a server-side rendered DOM? Most (if not all) of the cases people assert the static markup rendered. Since user interaction happens on the client, client tests should test it.

Does providing a `{ ssr: true }` option play nicely with the existing API? Are there any other options passed in a similar manner?

I think it's either making the `render` function smarter for the sake of unifying a rendering interface, or introducing a new API dedicated to SSR tests:

```js
import { serverRender } from 'react-testing-library'

it('should render on the server', () => {
  const markup = serverRender(<ComponentsTree />)
  assert(markup).toContain("something")
})
```

I'd expect that the testing library inherits the environment it's being run in, so it's still worth mentioning that one must ensure their tests are running in `node` environment. I think if we run `serverRender` in `jest`, for example, the execution environment would still be js-dom. Perhaps it doesn't matter much, but the closer your test is to the actual execution context the better, so in jest's case it'd be about setting the `jest-environment` parameter in the header comment of the test suite.

**Comment by kentcdodds** [comment]
Hi @kettanaito,

> When would you want to interact with a server-side rendered DOM?

I don't think you'd want to interact with it (and there wouldn't be any event handlers wired up anyway) but you might want to traverse it to make sure certain things are rendered properly.

> Does providing a `{ ssr: true }` option play nicely with the existing API? Are there any other options passed in a similar manner?

Yes, we currently also have `{ hydrate: true }`

I agree that anyone using this feature would want to make sure they're not running with a real DOM.

This actually brings up a good point. If you're running your tests outside a jsdom global environment (as you noted people should) then how would React Testing Library create a DOM node to give back to you. Presumably it would create a JSDOM instance, but that would require that we add JSDOM as a dependency of this project and I do not want to do that. So then we'd have to say that you'd have to provide your own instance of JSDOM and if you have to do that then what good is us providing an API for you? It doesn't really do much more than you could do yourself.

Hmmmmmmmmmmmm....

**Comment by kettanaito** [comment]
Hi, @kentcdodds 

I'm confused what would be the benefit of using `react-testing-library` API instead of a plain:

```js
import { renderToStaticMarkup } from 'react-dom/server'

const html = renderToStaticMarkup(<Component />)
expect(html).toContain('class-name')
```

**Comment by kentcdodds** [comment]
The benefit would be the ability to query the result like you do with regular front-end tests (using queries like `getByLabelText`). The problem is that we'd have to create a DOM for that.

I'm thinking that we should probably just put this in a separate package `@testing-library/react-server` which can have a dependency on jsdom to handle the creation of DOM nodes.

Thoughts?

**Comment by aw-davidson** [comment]
But does the user interact with server side rendered content before it reaches the browser? No. So, maybe the test setup needs to be rethought.

**Comment by kettanaito** [comment]
Since this kind of rendering is determined by the environment, I suggest not to have any explicit options like `ssr: true`, because they may contradict that very environment (i.e. testing SSR when being in a jsdom env).

Instead, `render()` could check the node environment and render to static markup correspondingly. Keeping the library's API consistent, the users would be able to use selectors like `getByLabelText`, as suggested by @kentcdodds.

**Comment by kentcdodds** [comment]
I'm sort of in favor of that idea, except in the case that someone *thinks* they're in a JSDOM environment but aren't really that could be really confusing. So I'd rather have something explicit and I'm thinking a separate package is the bet way forward.

Thanks for the discussion! So if anyone wants to take this over, please start the project yourself under your own github user and when it's stable, then let us know (here is fine) and we can talk about brining it into the org :)

Thanks a bunch!

**Comment by benmonro** [comment]
curious if anyone has seen / tried https://www.npmjs.com/package/happy-dom as it might be a potential way to do this...

**Comment by jrolfs** [comment]
I came across this issue while trying to figure out how to test server-specific behavior. The `{ ssr: true }` option looks like exactly what I would have needed, but I managed to come up with a solution for my use case without it.

I wanted to make sure to add it here in case it helps anyone else out. For context, the behavior I'm testing is a submit button that's disabled on the server render pass but then enabled via `useEffect` on the client.

```tsx
	// Mock stuff necessary for server environment

    const container = document.createElement('div');

    container.innerHTML = renderToString(
		// JSX markup (e.g: <form><MyButton /></form>)
    );

    document.body.appendChild(container);

    // Assert expected server markup (i.e: button is disabled, form does not submit)
    
    // Mock stuff necessary for client environment

    render(
      /* Identical JSX markup (e.g: <form><MyButton /></form>) */,
      { container, hydrate: true },
    );

    // Assert expected client behavior (i.e: button is enabled, form does submit)
```

I could be wrong but I'm pretty sure since I'm hydrating the same markup via `render(/* */, { hydrate: true })` I don't need to do any manual cleanup.

**Comment by connorjs** [comment]
@jrolfs - Do you have an example on GitHub using this pattern?

I like this idea a lot and tried it out locally, but using it in two test cases led to a `getByText` failure due to two instances. I had to add a clean-up step (`container.remove()`) to resolve this.

>I don't need to do any manual cleanup.

So, mostly interested in this part.

**Comment by angeloashmore** [comment]
Throwing out another possible solution if you're just looking to test the static output of a tree.

```typescript
import { test, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import { renderToString } from "react-dom/server";

test("sample static test", () => {
	const staticMarkup = renderToString(<button>Click me!</button>);

	render(<div dangerouslySetInnerHTML={{ __html: staticMarkup }} />);

	expect(screen.queryByRole("button")).toHaveTextContent("Click me!");
});
```

This lets you use Testing LIbrary's `screen` API in environments where `render` is already supported (e.g. `@testing-library/react`).

**Comment by kamleshchandnani** [comment]
> I came across this issue while trying to figure out how to test server-specific behavior. The suggested `{ ssr: true }` option looks like exactly what I would have needed, but I managed to come up with a solution for my use case without it.
> 
> I wanted to make sure to add it here in case it helps anyone else out. For context, the behavior I'm testing is a submit button that's disabled on the server render pass but then enabled via `useEffect` on the client.
> 
> ```tsx
> 	// Mock stuff necessary for server environment
> 
>     const container = document.createElement('div');
> 
>     container.innerHTML = renderToString(
> 		// JSX markup (e.g: <form><MyButton /></form>)
>     );
> 
>     document.body.appendChild(container);
> 
>     // Assert expected server markup (i.e: button is disabled, form does not submit)
>     
>     // Mock stuff necessary for client environment
> 
>     render(
>       /* Identical JSX markup (e.g: <form><MyButton /></form>) */,
>       { container, hydrate: true },
>     );
> 
>     // Assert expected client behavior (i.e: button is enabled, form does submit)
> ```
> 
> I could be wrong but I'm pretty sure since I'm hydrating the same markup via `render(/* */, { hydrate: true })` I don't need to do any manual cleanup.

@jrolfs, since you're using `render` from testing-library which as per the setup looks like is using `jsdom` so how will you catch things like usage of browser globals in these components for eg: `document`, `window`, etc. as these will be true and defined as your environment is `jsdom` and not `node`

**Comment by jrolfs** [comment]
@kamleshchandnani, you could probably achieve that behavior with a custom Jest environment, but it's not something I was particularly concerned about in what I was trying to test.

**Comment by ntucker** [comment]
> I'm sort of in favor of that idea, except in the case that someone _thinks_ they're in a JSDOM environment but aren't really that could be really confusing. So I'd rather have something explicit and I'm thinking a separate package is the bet way forward.

I'm using an explicit jest environment for node to ensure my hooks (that are used to run during SSR) work properly in that context.

**Comment by mihanizm56** [comment]
> > I'm sort of in favor of that idea, except in the case that someone _thinks_ they're in a JSDOM environment but aren't really that could be really confusing. So I'd rather have something explicit and I'm thinking a separate package is the bet way forward.
> 
> I'm using an explicit jest environment for node to ensure my hooks (that are used to run during SSR) work properly in that context.

how do you switch jest environments for ssr and regular csr in tests?
