### ISSUE TITLE
expect fail when testing css class with 'toHaveStyle'

### ISSUE THREAD

**Issue by danruziska** [testing-library/react-testing-library#563]
- `react-testing-library` version: 9.4.0
- `react` version: 16.12.0
- `node` version: 12.13.1
- `npm` (or `yarn`) version: yarn 1.19.2

### What you did:

I was creating a test to check the css style of a given component.

### What happened:

I'm using MaterialUI TableCell component, which has a class applied by default and I've overriden the color property to my custom theme. 

The test failed because the style the 'toHaveStyle' is getting is not what the user is actually seeing.

- Expected

-- color: rgb(3, 64, 187);  ----> this is the color applied by my custom theme (what the user is seeing)
++ color: rgba(0, 0, 0, 0.87); -----> this is the color added by MaterialUI but it's being overriden

### Reproduction:

https://codesandbox.io/s/quizzical-wozniak-c62l0

### Problem description:

I can't test a component with a style overriden

**Comment by eps1lon** [comment]
Thank you for opening this issue with a reproduction.

Unfortunately this is an issue with a third party dependency:

> I was creating a test to check the css style of a given component.

Testing styles with the most common setup (using JSDOM instead of a real browser) is very brittle. JSDOM does not fully implement cascading styles. Especially if specificity is involved JSDOM does not return accurate results.

If you want to test how something looks I suggest something like visual regression testing or waiting for JSDOM to implement cascading styles.

**Comment by johseffer** [comment]
@danruziska How did u solve your problem?

**Comment by jun-nguyen-goldenowl** [comment]
hi @danruziska, have you solved your problem?

**Comment by nickmccurdy** [comment]
You may want to use an end to end testing tool like Cypress or Puppeteer for this.

**Comment by gnapse** [comment]
Even if closed (and rightly so) I'll move this to jest-dom, as it fits better there.
