### ISSUE TITLE
CSS variables don't seem to be rendered

### ISSUE THREAD

**Issue by madou** [testing-library/react-testing-library#566]
- `react-testing-library` version: latest
- `react` version: latest
- `node` version: latest
- `npm` (or `yarn`) version: latest

### Relevant code or config:

```js
const { debug } = render(<div style={{ '--test': size }}>hello worlds</div>)
debug();
```

### What you did:

Test the above

### What happened:

CSS variables don't appear on the element (look in console from debug)

### Reproduction:

Run code above.

### Problem description:

I expected the styles to be available like they would be in the browser - they aren't currently.

### Suggested solution:

🤷‍♂ make them resolve? i'll have to dig into the code to see why they aren't there.

its more than likely related to https://github.com/jsdom/jsdom/issues/1895 - maybe theres nothing we can do right now :/

**Comment by kentcdodds** [comment]
Hi @madou,

You can definitely use Testing Library tools with css variables. The problem is where you're running the tests. If you're using JSDOM then that issue is probably your problem. But you could run this with Karma in a real browser, or with Cypress and those would work fine I expect.

There's nothing we can do about it in this project. Sorry. Good luck!

**Comment by madou** [comment]
Hi you're right! The last bit of the issue points to their open issue about it.

No worries - thanks Kent.
