### ISSUE TITLE
mock preventDefault

### ISSUE THREAD

**Issue by benmonro** [testing-library/react-testing-library#572]
Not sure if this is a bug or by design but thought i'd post here to make sure either way.  I was asked if its possible to ensure that preventDefault was called using a mock.

- `react-testing-library` version: latest
- `react` version: latest
- `node` version: 12
- `npm` (or `yarn`) version: 6

### Relevant code or config:

```jsx
import React from "react";
import { render, fireEvent } from "@testing-library/react";

it("should prevent default on mousedown", () => {
  const { getByText } = render(
    <button
      onClick={e => {
        console.log("called");
        e.preventDefault();
      }}
    >
      click me
    </button>
  );

  const mockEvent = { preventDefault: jest.fn() };
  fireEvent.click(getByText("click me"), mockEvent);
  expect(mockEvent.preventDefault).toBeCalled();
});

```

### What you did:
tried to mock the preventDefault function (see above)

### What happened:
mock is not called

### Reproduction:

https://codesandbox.io/s/laughing-kilby-6thj3
### Problem description:
not sure if it's a problem or by design, but is it possible to ensure that a button event calls preventDefault?

**Comment by eps1lon** [comment]
> not sure if it's a problem or by design, but is it possible to ensure that a button event calls preventDefault?

It's hard to suggest a better solution since it's already trivial to do in the code you posted since you already own the onClick handler.

In the components I tested the test did now own the click handler that called preventDefault. However, the component accepted an additional handler that is called after the handler that calls preventDefault. For that case asserting on `defaultPrevented` seemed like the best solution IMO.

Start of test: https://github.com/mui-org/material-ui/blob/0ccca2cc229fdcfc795af8aeed063bf5ddc0f65f/packages/material-ui/src/ButtonBase/ButtonBase.test.js#L702
assertion: https://github.com/mui-org/material-ui/blob/0ccca2cc229fdcfc795af8aeed063bf5ddc0f65f/packages/material-ui/src/ButtonBase/ButtonBase.test.js#L718
why the assertion "works": https://github.com/mui-org/material-ui/blob/0ccca2cc229fdcfc795af8aeed063bf5ddc0f65f/packages/material-ui/src/ButtonBase/ButtonBase.test.js#L703

It's not that easy to read since I suspect you need read the start again when trying to understand the assertion. Time will tell if it's actually a good test.

If you cannot pass a onClick handler I would suggest wrapping the component under test in an additional element and check the bubbled event e.g. `<div onClick={asserDefaultPrevented}><ComponentUnderTest /></div>`. Though the second test also has the implicit assertion that the click event was allowed to propagate i.e. the ComponentUnderTest did not call `event.stopPropagation`.

**Comment by kentcdodds** [comment]
Hi friends,

If @eps1lon hadn't said what he said, I would have typed basically every single thing he typed. 👍

**Comment by cpuy** [comment]
Hi there.

IMHO I would rather use the [createEvent](https://testing-library.com/docs/dom-testing-library/api-events#createeventeventname) method and assert on `event.defaultPrevented`

```
const myEvent = createEvent.click(getByText("click me"))

fireEvent(getByText("click me"), myEvent)

expect(myEvent.defaultPrevented).toBeTruthy()
```

**Comment by gugol2** [comment]
> Hi there.
> 
> IMHO I would rather use the [createEvent](https://testing-library.com/docs/dom-testing-library/api-events#createeventeventname) method and assert on `event.defaultPrevented`
> 
> ```
> const myEvent = createEvent.click(getByText("click me"))
> 
> fireEvent(getByText("click me"), myEvent)
> 
> expect(myEvent.defaultPrevented).toBeTruthy()
> ```

Sorry but that does not work for me. Maybe `defaultPrevented` is truthy by default.

For some reason it is difficult to intercept the `React.SyntheticEvent` from a button.

**Comment by sandrina-p** [comment]
@gugol2, have you find a solution? I'm facing the same scenario...

**Comment by gugol2** [comment]
> @gugol2, have you find a solution? I'm facing the same scenario...

Hi!
It has been some time since my last answer here. Maybe you could do a CodeSandbox to better explain your scenario.

**Comment by sandrina-p** [comment]
@gugol2, it's similar to yours. I have a form component with `onSubmit`, but the submit button is outside the form component. My question is how to simulate the form submit event. I'll try to create a sandbox later this/next week :)

**Comment by rafee-selise** [comment]
Another way of doing it is to mock preventDefault. It works for stopprogation as well. 

PreventDefault:
```
const myEvent = createEvent.click(getByText("click me"))
myEvent.preventDefault = jest.mock();
fireEvent(getByText("click me"), myEvent)
expect(myEvent.preventDefault).toHavebeenCalled()
```
StopPropagation
```
const myEvent = createEvent.click(getByText("click me"))
myEvent.stopPropagation= jest.mock();
fireEvent(getByText("click me"), myEvent)
expect(myEvent.stopPropagation).toHavebeenCalled()
```

**Comment by mdrafee03** [comment]
Another way of doing it is to mock preventDefault. It works for stopprogation as well. 

PreventDefault:
```
const myEvent = createEvent.click(getByText("click me"))
myEvent.preventDefault = jest.mock();
fireEvent(getByText("click me"), myEvent)
expect(myEvent.preventDefault).toHavebeenCalled()
```
StopPropagation
```
const myEvent = createEvent.click(getByText("click me"))
myEvent.stopPropagation= jest.mock();
fireEvent(getByText("click me"), myEvent)
expect(myEvent.stopPropagation).toHavebeenCalled()
```

**Comment by zyqxd** [comment]
For some reason, `createEvent.keyDown` does not allow passing of `key` 

```
"@testing-library/react": "12.1.2",
```


Example
```ts
// Handler
function useEventHandler() {
  React.useEffect(() => {
    const eventListener = (event) => {
      console.log('keydown', event.key); // Console check
  
      if (event.key !=='a') return;
  
      event.preventDefault();
    }
  
    target.addEventListener('keydown', eventListener);
  
    return () => {
      target.removeEventListener('keydown', eventListener);
    };
  }, []);
}

// Spec
const fn = jest.fn();
const { container } = render(<div />);
const keyEvent = createEvent.keyDown(container, { key: 'a' });

renderHook(() => useEventListener());
act(() => {
  fireEvent.keyDown(container, keyEvent);
});

expect(keyEvent.defaultPrevented).toBe(true);
```

Output 
```
  console.log
      keydown // < undefined key

  useKeyDown › calls preventDefault when fn is called

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      116 |
    > 118 |     expect(keyEvent.defaultPrevented).toBe(true);
          |                                       ^
      119 |   });
      120 | });
```

**Comment by rohit-kumar-globant** [comment]
good
