### ISSUE TITLE
We should add a way to compose the render method

### ISSUE THREAD

**Issue by pedroapfilho** [testing-library/react-testing-library#578]
### Problem

When you're using `styled-components` or the `Context API`, for example, you have to wrap your component with another component, to add these values.

```jsx
const Wrapper = ({children}) => (
	<StyleProvider theme={theme}>
		<ContextProvider value={value}>
			{children}
		</ContextProvider>
	</StyledProvider>
)

const {getByText} = render(<Wrapper><Component /></Wrapper>)

...
```
It's good to mention that we have to create this helper for the `rerender` too.

### Suggested implementation:

I would like to have a way to natively customise the `render` method, and add the wrappers that I want to on it.

### Describe alternatives you've considered:

What usually happens is that we create a function to do so, like a `renderer`, that adds these values for us, so we only use the `render` method on this function.

### Teachability, Documentation, Adoption, Migration Strategy:

We could add a function to customise the render method, so it would be used by the `rerender` too, like:

```jsx
import {customizeRender} from "@testing-library/react"

customizeRender(Wrapper)
```

**Comment by kentcdodds** [comment]
Hi @pedroapfilho,

Thanks for the issue, but I don't think that it's worthwhile to implement something like this because you typically should just have a single place where you [specify the wrapper](https://testing-library.com/docs/react-testing-library/api#wrapper) and all providers for your app: https://testing-library.com/docs/react-testing-library/setup#custom-render

I don't think that we need any more API than that. Thanks!
