### ISSUE TITLE
container.querySelector always returns null

### ISSUE THREAD

**Issue by mhuggins** [testing-library/react-testing-library#629]
- `DOM Testing Library` version: 7.0.3
- `node` version: 10.19.0
- `npm` (or `yarn`) version: npm 6.13.4

### Relevant code or config:

```js
const { container, debug } = render(<FormModal isOpen />);
const el = container.querySelector(selector);

console.log(document.querySelector('div'));
// => HTMLElement< ...snip... >

console.log(el.querySelector('div'));
// => null

debug();
// => <div> ...snip... </div>
```

### What you did:
Using `@testing-library/react`, I'm attempting to use the `container` object returned by the `render` function to query for an ambiguous DOM element.

### What happened:
Unfortunately, `querySelector` *always* returns `null` no matter what selector I pass to it.  However, if I use `document.querySelector`, it works as expected.

### Problem description:
The provided documentation doesn't match what is necessary to make this work.

### Suggested solution:
Fix it somehow, but I'm not sure why it's not working.  The `getByXXX` functions being returned by the `render` function work as expected.

**Comment by kentcdodds** [comment]
It definitely is. It's hard to say whether this is a bug in Testing Library or not without an actual reproduction.

**Comment by adamchenwei** [comment]
use `screen` generated by render will receive `TypeError: Cannot read property 'querySelector' of undefined`
Is the suggestion outdated?

**Comment by MatanBobi** [comment]
> use `screen` generated by render will receive `TypeError: Cannot read property 'querySelector' of undefined`
> Is the suggestion outdated?
> 
> Well, the only way works is using `document` directly inside test execution. in case anyone see this

@adamchenwei,
That's true, as @kentcdodds mentioned [here](https://github.com/testing-library/react-testing-library/issues/629#issuecomment-608673888),
`screen` contains our queries and if really don't want to use them, `querySelector` is on the `document` object..

**Comment by FerhatAvdic** [comment]
Same thing happened to me when i rendered a modal

**Comment by Hiroki111** [comment]
Same thing happened to me when I tried to access an element that's rendered by a function called from `map`. 

The component that I test looks like...

```
export function Component() {
  // other lines here
  function getAvatarContent(staff) {
    if (staff.id === ALL_STAFF.id) {
      return <PeopleIcon className='people-icon'/>;
    }
    // return string based on "staff"
  }

  return (
   <div>
     {staffOptions.map((staff) => (
        {getAvatarContent(staff)}
      ))}
   </div>
  );
}
// "staffOptions" is an array and it always has "ALL_STAFF" object.
// So, "getAvatarContent" function must return PeopleIcon at least once
```

The test case looks like...

```
const { container } = render(<Component />);

// This works
await waitFor(() => expect(document.querySelector('.people-icon')).toBeInTheDocument());

// This fails 
await waitFor(() => expect(container.querySelector('.people-icon')).toBeInTheDocument());
```

`PeopleIcon` is from [@mui/icons-material/Menu](https://mui.com/material-ui/material-icons/). 
At first, I thought that this icon component had an issue. However, if I render this icon outside the `staffOptions.map`, `container.querySelector('.people-icon')` didn't fail.

So, the culprit seems to be `container.querySelector` to me

**Comment by dwbra** [comment]
Issue still remains for when rendering a Modal

**Comment by mrbinky3000** [comment]
2025 and the issue still seems to happen with modals.   I can use `debug()` to show the rendered HTML and the class name I'm trying to query for using `container.querySelector()` is absolutely there in the `debug()` output.  But for some reason `querySelector()` can't find the class name.  I thought perhaps there was a race condition and the modal might not be rendered yet, so I made the test async and it still fails. 

It seems only `document.querySelector()` works.  This only happens when I work with a modal, specifically React-Modal.
