### ISSUE TITLE
fireEvent.mouseEnter/Leave don't trigger React component's onMouseEnter/Leave

### ISSUE THREAD

**Issue by robyn3choi** [testing-library/react-testing-library#630]
- `@testing-library/react` version: 9.4.1
- `react` version: 16.9.0
- `node` version: 12.16.1
- `yarn` version: 1.19.1

### Relevant code or config:

```js
import React from "react";
import { render } from "@testing-library/react";
import { fireEvent } from "@testing-library/dom";

function SomeComponent({ handleEnter, handleLeave }) {
  return <div aria-label="test-div" onMouseEnter={handleEnter} onMouseLeave={handleLeave} />;
}

test("test mouse events", () => {
  const mockHandleEnter = jest.fn();
  const mockHandleLeave = jest.fn();

  const { getByLabelText } = render(<SomeComponent handleEnter={mockHandleEnter} handleLeave={mockHandleLeave} />);

  fireEvent.mouseEnter(getByLabelText("test-div"));
  expect(mockHandleEnter).toHaveBeenCalled();

  fireEvent.mouseLeave(getByLabelText("test-div"));
  expect(mockHandleLeave).toHaveBeenCalled();
});
```

### What you did:

run `yarn test`

### What happened:

Both assertions fail with 
```
Expected number of calls: >= 1
Received number of calls:    0
```

### Reproduction:
Here's a codesandbox but for some reason, it renders the test div twice here:
https://codesandbox.io/s/react-testing-library-demo-tv41v

### Problem description:

I need a way to test `onMouseEnter` and `onMouseLeave` in my React components.

### Suggested solution:
`fireEvent.click()` does successfully trigger the component's `onClick` if it has one.

**Comment by itsnorbertkalacska** [comment]
Dear @robyn3choi,

The problem here is that you import `fireEvent` from `@testing-library/dom` and NOT from `@testing-library/react`. You need to import `fireEvent` from `@testing-library/react` when testing React apps.

React event system tracks native mouseOver/mouseOut events for running onMouseEnter/onMouseLeave handlers. So you either import `fireEvent` from this library or if you want to use the one from `@testing-library/dom` you need to fire `mouseOver` and `mouseOut`. 

If you look at the source code it actually explains why this is like that: https://github.com/testing-library/react-testing-library/blob/master/src/pure.js#L130

Hope it helped!

**Comment by robyn3choi** [comment]
thanks!!
