### ISSUE TITLE
@testing-library/dom dependecy issue

### ISSUE THREAD

**Issue by clonitza** [testing-library/react-testing-library#650]
- `@testing-library/react` version: 10.0.3
- `react` version: 16.3.1
- `node` version: 12
- `npm` (or `yarn`) version: 1.19

### What you did:

Upgraded `@testing-library/dom` to 7.2.1

### What happened:

 `@testing-library/dom` `configure` doesn't set the `testIdAttribute` anymore

### Problem description:

There are two entries created in yarn.lock for `@testing-library/dom`, one for 7.1.0 (used by @testing-library/react) and one for 7.2.1

### Suggested solution:

Bump `@testing-library/dom` dependency to 7.2.1

**Comment by eps1lon** [comment]
You probably have a an explicit dependency on `@testing-library/dom` in your package.json (or another packages requires it).

Bumping it might very well cause issues in other dependency trees which is why this wouldn't be safe. It's also not maintainable since we'd need to publish new versions whenever on of our dependency gets a new release.

You need to de-duplicate this yourself. In your case removing each lockfile entry for `@testing-library/dom` and then running `yarn` should help.

**Comment by clonitza** [comment]
Ok, I'll use the resolutions and freeze the version.
