### ISSUE TITLE
@testing-library/dom 7.17.1 is no longer available in npm registry

### ISSUE THREAD

**Issue by ryuuji3** [testing-library/react-testing-library#748]
- `@testing-library/react` version: 10.2.1
- Testing Framework and version: jest 24.8.0
  
- DOM Environment:
  

### Relevant code or config:

package.json
```json
"devDependencies": {
    "@testing-library/jest-dom": "^5.10.0",
    "@testing-library/react": "^10.2.1",
    "@testing-library/user-event": "^11.4.1"
  }
```

### What you did:

Attempted to install @testing-library/react 10.2.1

### What happened:

Failed to install because required dependency (@testing-library/dom 7.17.1) is not published to npm

![image](https://user-images.githubusercontent.com/9097492/87803344-55126900-c820-11ea-8cae-ce3ae4430cf6.png)

### Problem description:

Was trying to re-install a private repository, and it failed to install because of @testing-library dependencies

**Comment by kentcdodds** [comment]
Hi @ryuuji3, I'm guessing you've got some proxy that's having trouble because this is definitely on the registry:

- https://github.com/testing-library/dom-testing-library/releases/tag/v7.17.1
- https://www.npmjs.com/package/@testing-library/dom/v/7.17.1
- https://unpkg.com/@testing-library/dom@7.17.1/

Sorry, I'm afraid there's nothing that we can do here :-/

**Comment by kentcdodds** [comment]
No worries 😁
