### ISSUE TITLE
Unit tests purity vs. testing the user output

### ISSUE THREAD

**Issue by alirezanobahari** [testing-library/react-testing-library#814]
The team I'm working with mocks every single component and hook used inside the component for all tests to make the tests pure. for example in a component like

```
function Parent() {
  useAHook();
  return (
    <div>
      <ComponentA />
      <ComponentB />
    </div>
  );
}
```

all useAHook, ComponentA, and ComponentB are mocked inside the test with their simpler versions.
is it a good approach for unit testing?

**Comment by eps1lon** [comment]
> is it a good approach for unit testing?

It follows the technical definition of a unit test, sure. I think every testing-library maintainer has made the experience that this approach doesn't provide useful tests (debugging, breaks  when user-observable behavior breaks) in React.

What you're doing is much more similar to enzyme's shallow rendering. 

Either way, you're looking for a recommendation on the testing approach. Since testing-library is not built to support shallow rendering, you're getting biased recommendations.

[Our intro](https://testing-library.com/docs/react-testing-library/intro) makes an argument against testing implementation details so that's a better starting point than a GitHub issue. Beyond that our [discord community](https://testing-library.com/discord) might help you if something about the approach is unclear.

**Comment by alirezanobahari** [comment]
@eps1lon Thanks 🙏
