### ISSUE TITLE
getByTag

### ISSUE THREAD

**Issue by Bikeman868** [testing-library/react-testing-library#853]
This has been discussed before, but I strongly disagree with the outcome of the previous discussion.
In my case I am testing a React component that matches urls in the text and wraps them in anchor tags.

For example `"One, two https://example.com/ three"` would be rendered as `<span>One, two, <a href="https://example.com/">https://example.com/</a> three</span>`.

It's not a good enough test to check for the existence of the text `https://example.com/` because this would be in the document even if my component just output the original text unmodified.

The presence of the anchor tag is absolutely something that the user can see.

Your stubborn refusal to implement `getByTag` makes no sense to me. This would add to the richness of the library and take nothing away from the principals on which it is built.

**Comment by afontcu** [comment]
There are several ways to test that scenario:

1) `expect(getByRole('link')).toHaveAttribute('href', 'https://example.com/')`
2) Make your component add a `data-testid` attribute and query it.

If either of these solutions suits your needs feel free to close the issue 😃

**Comment by alexkrolick** [comment]
`getByRole` is the solution here. `role` and `accessibleName` (`getByRole('link', { name: 'https://example.com' })`) make sure the site is working from an accessibility perspective, as well as being resilient to alternative implementations that have the same semantics but different DOM structure.

We don't want to add a tag/xpath utility because it makes it easy to fall back on `div:nth-child(2) > span > a` type queries that are a common source of brittleness and frustration in other libraries, from Selenium to Enzyme to Cypress. 

As you know if you've read the previous discussion, `querySelector` or an `inlineSnapshot` assertion can get you around this safeguard.
