### ISSUE TITLE
Is it possible to render a component and do some tests between useLayoutEffect and useEffect

### ISSUE THREAD

**Issue by leobastiani** [testing-library/react-testing-library#859]
I think it would be great to stop rendering between useLayoutEffect and useEffect, the benefits could be: 

- Test that my component is using useLayoutEffect rather than useEffect
- Test that useEffect has the right state before it starts
- Test isolation of useLayoutEffect and useEffect rather than testing both

Thank you!

**Comment by balavishnuvj** [comment]
isn't that components implementation? Will you be able to test the final output?

**Comment by MatanBobi** [comment]
Hi @leobastiani, thanks for posting this one here! :)
I agree with what @balavishnuvj wrote, this is a way to test an implementation detail of the component which is something we don't want to encourage.
We'd want to test use-cases from the user's perspective so what does the user see between the effects you're trying to test? Can you test that?

**Comment by eps1lon** [comment]
```jsx
act(() => {
  render(<Component />)

  expect(screen).toHaveLayoutEffectsApplied();
});

expect(screen).toHavePassiveEffectsApplied();
```

`expect(screen).toHaveLayoutEffectsApplied();` is pseudo code for whatever assertion that is true after layout effects and `expect(screen).toHavePassiveEffectsApplied();` contains assertions that are only true after passive effect.

> isn't that components implementation? 

It is, but the behavior is observable by a user.

**Comment by leobastiani** [comment]
> It is, but the behavior is observable by a user.

Exactly

**Comment by leobastiani** [comment]
I tried to implement a test a hook which I had to replace useEffect to useLayoutEffect and I couldn't find how to test it with react-testing-library. So I came up with this solution:

https://github.com/pmndrs/zustand/pull/280/files

**Comment by leobastiani** [comment]
I suggest to create a new renderOption like
```javascript
render(<Component />, { flushUseEffects: false })
```

I also could manage to make a PR if it sounds good.

**Comment by eps1lon** [comment]
`flushUseEffects` is probably misleading compared to naming it just `act: false`.

However, I'm not we should add this option. This is the first time we hear about this so I would let this sit for a while until we here more about the problem and interest in solving it. Especially since `render` is just a thin wrapper around `ReactDOM.render`. You probably don't need 80% of that code anyway.

**Comment by LukasBombach** [comment]
I completely understand the notion of testing behavior that is observable by a user as opposed to testing implementation details.

Now we do have an issue where I think we need to test a non-user feature which relates to SSR:

* We do render a [WebShare Button](https://web.dev/web-share/) only when the user's browser supports this feature
* We also do SSR
* Servers do not support WebShare, or to be precise, has no knowledge of it will be supported by the user opening the page
* The server will not render the button
* Now a client loads the page, supports WebShare and renders the button
* 💥 DOM mismatch during hydration 💥
* Performance decreases

To adress this, we put the check for the WebShare API inside useEffect:

```tsx
const WebShare: VFC = () => {
  const [hasShareApi, setHasShareApi] = useState(false);

  useEffect(() => {
    if (typeof navigator !== 'undefined' && navigator.share) {
      setHasShareApi(true);
    }
  }, []);

  if (!hasShareApi) {
    return null;
  }

  return <Button >...</Button>;
};
```

This little trick will

* Not render the button on the server
* Not render the button on the client
* 💘 Hydration is happy 💘
* After the button has been rendered the WebShare api will be checked and the button will be rendered (probably)

Now the tests for this fail because`useEffect` has become transparent, _a mismatch to React's expected behavior_ (which might be a debatle problem).

To address this, we tried to mock useEffect

```tsx
test(`WebShare gets revealed only after useEffect has run
        reason: WebShare will never be rendered on the server.
        If the client were to render it directly we would get a DOM mismatch during hydration
        and would have to suffer a hefty performance impact`, () => {
  const useEffectSpy = jest.spyOn(React, 'useEffect').mockImplementation(() => {});
  navigator.share = jest.fn().mockResolvedValue(undefined);
  const { container } = render(<Share.WebShare />);

  expect(useEffectSpy).toHaveBeenCalled();
  expect(container).toBeEmptyDOMElement();

  useEffectSpy.mockRestore();
  expect(render(<Share.WebShare />).container).not.toBeEmptyDOMElement();
});
```

This did work until now ([but only if we imported React as `import * as React from "react";`](https://github.com/facebook/jest/issues/6972#issuecomment-814221767)) but not things have changed, `useEffect` is gone (I guess you're babeling it away?).

Anyhow, that is a pickle. Any advice here?

**Comment by eps1lon** [comment]
> Anyhow, that is a pickle. Any advice here?

```js
const container = document.getElementById('react-root');

const markup = ReactDOMServer.renderToString(<App />);
container.innerHTML = markup;

// make assertions on `container` about SSR

act(() => {
	ReactDOM.hydrate(<App />, container);

	// make assertions on `container` about hydration
});

// make assertions on `container` after it yielded once and flushed effects

```

The above code requires no React implementation details. Though I haven't into how this would look in modern roots.

**Comment by LukasBombach** [comment]
Just out of curiosity: How do you omit `useEffect`? Because I cannot find it in your code.

**Comment by eps1lon** [comment]
> Just out of curiosity: How do you omit useEffect? Because I cannot find it in your code.

Why is `useEffect` relevant in this test? You can make assertions about its behavior with my pattern. Just not with too generic expectations like "it has been called". What you'd want to test is what the effect does which already implies that it has been called.

**Comment by eps1lon** [comment]
React already provides the necessary tools to test this sort of behavior (see https://github.com/testing-library/react-testing-library/issues/859#issuecomment-757463037 and https://github.com/testing-library/react-testing-library/issues/859#issuecomment-839619380). 

There isn't a strong case to support this in the core library since this is dangerously close to testing implementation details. We'll keep an open mind about it. Though please understand that we always need to consider how an API could be misused and this is close to it.

**Comment by zaqqaz** [comment]
> ```js
> act(() => {
>   render(<Component />)
> 
>   expect(screen).toHaveLayoutEffectsApplied();
> });
> 
> expect(screen).toHavePassiveEffectsApplied();
> ```
> 
> `expect(screen).toHaveLayoutEffectsApplied();` is pseudo code for whatever assertion that is true after layout effects and `expect(screen).toHavePassiveEffectsApplied();` contains assertions that are only true after passive effect.
> 
> > isn't that components implementation?
> 
> It is, but the behavior is observable by a user.

Just wanted to follow up on it as I can see here

> act(() => {
>   render(<Component />)
> 
>   expect(screen).toHaveLayoutEffectsApplied();
> });

expect(screen).toHaveLayoutEffectsApplied(); - Won't work as layout effect not yet applied and will be applied after act (version tested: 13.2.0 and 16.0.0)
