### ISSUE TITLE
does not play well with jest 27

### ISSUE THREAD

**Issue by TrejGun** [testing-library/react-testing-library#918]
- `@testing-library/react` version: 

"@testing-library/jest-dom": "5.12.0",
"@testing-library/react": "11.2.7",

- Testing Framework and version:

"jest": "27.0.1",

  
- DOM Environment:

jsdom

  

### Relevant code or config:

please refer to this project
https://github.com/TrejGun/casino

### What you did:

updated jest from 26 to 27

### What happened:

Tests are now failing with 
```
    ReferenceError: clearImmediate is not defined
```

### Reproduction:

see above

### Problem description:

Tests are failing :(

### Suggested solution:

N/A

**Comment by ediblecode** [comment]
@TrejGun it looks like this was a breaking change in Jest 27, see https://github.com/facebook/jest/blob/master/CHANGELOG.md#fixes-2. Specifically:

> [jest-environment-jsdom] [BREAKING] Remove Node globals setImmediate and clearImmediate [#11222](https://github.com/facebook/jest/pull/11222)

See also https://github.com/testing-library/dom-testing-library/issues/914 which looks related.

**Comment by andrevenancio** [comment]
I'm getting `TypeError: Cannot destructure property 'AsymmetricMatcher' of '_prettyFormat.default.plugins' as it is undefined.`

**Comment by tdeekens** [comment]
Seeing the same problems. Will be even be possible for rtl to work in v26 and v27 of Jest with the same version?

**Comment by dodoongtak** [comment]
[Date: 2 June 2021]

with RTL:

```
//dev dep
"@testing-library/jest-dom": "^5.12.0",
"@testing-library/react": "^11.2.7",
"jest": "^27.0.3",

//dep
"react": "^17.0.2",
```

After updating jest version: 26 -> 27

Following Error Message Prompts out.
>The error below may be caused by using the wrong test environment. See https://jestjs.io/docs/configuration#testenvironment-string.
>
>Consider using the "jsdom" test environment.
>
> ReferenceError: document is not defined

---
As I've looked over the PRs mentioned this issue, 

@kentcdodds has already recognized the issue regarding the jest27 updates on switching default test env from `jsdom` to `node.`  
Discussion here: https://github.com/kentcdodds/kcd-scripts/pull/210

Applause for @eps1lon 👏👏👏

---

Unfortunately, I could not clearly figure out the future action plan to resolve this breaking change of jest.

1. **Would it be switching to `node` as default test env in testing-library?**

Or

2. As mentioned in the [jest blog post regarding 27update](https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults), we still can configure testEnvironment as `jsdom` instead of `node.`  

**Would it be still using jsdom though they suggest node?**

FYI:
The flipping default - Breaking Change started with this [PR](https://github.com/facebook/jest/pull/9874)

**Comment by m4thieulavoie** [comment]
Having the same issue after upgrading to Jest@27. Is anyone working on a fix?

**Comment by eps1lon** [comment]
> Having the same issue after upgrading to Jest@27. Is anyone working on a fix?

We're in the process of fixing this in `@testing-library/dom`. This particular issue should already be fixed in the alpha but it'll take some time to test it before we can release a new major of `@testing-library/react`.

**Comment by jRichardeau** [comment]
Hello,

Facing same issue but it seems to work for `@testing-library/dom` < `7.29.6`, so when forcing the `7.29.5` version in the dependencies of my `package.json` it solved my problem.

**Comment by tdeekens** [comment]
Same issues here but also not only rtl related.

1. Promises: native Promises (not polyfilled) do not seem to be controlable by Jest v27 making tests fail
2. Timers: the internal change to use sinon (in v27) seems to have the impact of jest not being able to control time when using core-js (it does overwrite some thing)

It turned out that disabling core-js under test for us was generally a good idea. However, leaving us with the issue that jest v27 seems to struggle with native promises.

**Comment by eps1lon** [comment]
Closed in https://github.com/testing-library/react-testing-library/pull/931

**Comment by eps1lon** [comment]
:tada: This issue is fixed in version 12.0.0-alpha.2 :tada:

The release is available on:
- `npm package (@alpha dist-tag)`
- [GitHub release](https://github.com/testing-library/react-testing-library/releases/tag/v12.0.0-alpha.2)

**Comment by maximeNaulleau** [comment]
I got this error :
`TypeError: Cannot destructure property 'AsymmetricMatcher' of '_prettyFormat.default.plugins' as it is undefined`

My packages installed :
```
@testing-library/react@12.0.0
@testing-library/dom@8.1.0
jest@27.0.6
ts-jest@27.0.3
```

**Comment by MatanBobi** [comment]
> I got this error :
> `TypeError: Cannot destructure property 'AsymmetricMatcher' of '_prettyFormat.default.plugins' as it is undefined`
> 
> My packages installed :
> 
> ```
> @testing-library/react@12.0.0
> @testing-library/dom@8.1.0
> jest@27.0.6
> ts-jest@27.0.3
> ```

@maximeNaulleau Can you please share which version of `pretty-format` you have installed? It should be 27^.

**Comment by signal-intrusion** [comment]
@MatanBobi I get the same error. I installed pretty-formatter@27.0.6.

```
@amzn/bui-react@2.0.0 /Users/plummer/dev/BUI/src/BUI/packages/bui-react
├── @amzn/bui-light@2.0.188
├── @amzn/bui-style-tokens@2.0.188
├── @babel/cli@7.14.5
├── @babel/core@7.14.6
├── @babel/preset-env@7.14.7
├── @babel/preset-react@7.14.5
├── @testing-library/react@12.0.0
├── @testing-library/user-event@13.2.0
├── @types/debug@4.1.6
├── @types/enzyme@3.10.9
├── @types/jest@26.0.24
├── @types/lodash@4.14.171
├── @types/react-datepicker@3.1.8
├── @types/react-dom@17.0.9
├── @wojtekmaj/enzyme-adapter-react-17@0.6.3
├── camelize@1.0.0
├── core-js@3.15.2
├── debug@4.3.2
├── enzyme@3.11.0
├── enzyme-adapter-react-16@1.15.6
├── jest@27.0.6
├── keyboardjs@2.6.4
├── lodash@4.17.21
├── nanoid@3.1.23
├── pretty-format@27.0.6
├── prop-types@15.7.2
├── UNMET PEER DEPENDENCY react@17.0.2
├── react-datepicker@3.8.0
├── UNMET PEER DEPENDENCY react-dom@17.0.2
├── react-input-autosize@3.0.0
├── react-intl@5.20.4
├── react-test-renderer@17.0.2
├── recompose@0.30.0
└── typescript@4.3.5
```

**Comment by MatanBobi** [comment]
> pretty-format@27.0.6

You don't need to install it on your own, it should be a dependency for [`testing-library/dom`](https://github.com/testing-library/dom-testing-library/blob/main/package.json#L49).
Can you run `npm ls pretty-format` and share the result please?
