### ISSUE TITLE
ToHaveFocus does not work when focusing child element of ref

### ISSUE THREAD

**Issue by mancristiana** [testing-library/react-testing-library#946]
- `@testing-library/react` version: 11.2.2
- Testing Framework and version:
`jest` with `react-scripts` 4.0.3
- DOM Environment:
`@testing-library/jest-dom`: 5.11.4 

### Relevant code or config:

I have a dialog that traps focus once it's open. In the browser, this works as expected.
```js
import React, {useState} from 'react'
import {useFocusTrap} from '@mantine/hooks'

export function App() {
  const ref = useFocusTrap()
  const [isOpen, setIsOpen] = useState(false)

  return (
    <div>
      <button onClick={() => setIsOpen(true)}>Open</button>
      {isOpen && (
        <div role="dialog" ref={ref}>
          Dialog
          <button onClick={() => setIsOpen(false)}>Close</button>
        </div>
      )}
    </div>
  )
}

```

 However, when I try to test that the close button has focus, this does not work.
```js
import React from 'react'
import {render, screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {App} from './App'

it('should focus close button when opening dialog', () => {
  render(<App />)
  userEvent.click(screen.getByRole('button', {name: 'Open'}))
  expect(screen.getByRole('dialog')).toBeInTheDocument()
  expect(screen.getByRole('button', {name: 'Close'})).toHaveFocus()
})
```

### What you did:
I tried to test that when opening the dialog, the close button gets focused.

### What happened:
In the test environment, the open button is still focused.
```
expect(element).toHaveFocus()

Expected
  <button>Close</button>
Received:
  <button>Open</button>

   7 |   render(<App />)
   8 |   userEvent.click(screen.getByRole('button', {name: 'Open'}))
   9 |   expect(screen.getByRole('dialog')).toBeInTheDocument()
> 10 |   expect(screen.getByRole('button', {name: 'Close'})).toHaveFocus()
  11 | })
```

### Reproduction:

https://codesandbox.io/s/rtl-to-have-focus-issue-yiq8v?file=/src/App.test.js

### Problem description:

The `toHaveFocus` behaves unexpectedly.
You can see the implementation of [useFocusTrap](https://github.com/mantinedev/mantine/blob/master/src/mantine-hooks/src/use-focus-trap/use-focus-trap.ts). Oversimpliefied, it focuses the first tabbable or focusable element inside the dialog.
```
const children = Array.from<HTMLElement>(node.querySelectorAll(FOCUS_SELECTOR));
focusElement = children.find(tabbable) || children.find(focusable) || null;
focusElement.focus();
```

### Suggested solution:

?

**Comment by eps1lon** [comment]
Thanks for the feedback.

> You can see the implementation of useFocusTrap. Oversimpliefied, it focuses the first tabbable or focusable element inside the dialog.

I suspect that the issue is rather with the testing environment. Assuming you're using `JSDOM` (e.g. via `jest`), elements will not take up any layout. [`useFocusTrap` considers these elements not tabbable](https://github.com/mantinedev/mantine/blob/6d6d953484bd28388826868d512b82161518aafa/src/mantine-hooks/src/use-focus-trap/tabbable.ts#L4-L12). Note that this is incorrect if you want to mimic browser behavior: [Elements with no dimensions are tabbable](https://codesandbox.io/s/zero-dimension-elements-are-tabbable-0n1sg). 

They also seems to have a workaround by setting `process.env.NODE_ENV` to `test`.

Could you debug `tabbable` in the browser and your test and check if they return different results? If so then you should either adjust your test environment or use a different library depending on what you're trying to solve with `useFocusTrap`.

**Comment by eps1lon** [comment]
Closing since no response was given in over 1 month.
